/* Symptom search: every search term and where it sends the patient.
   Source: Dr Vijay Manivel's change instructions, 3 October 2026 (item 3.2).
   Clinical content: a draft until Dr Manivel signs it off.

   Each row is [term, outcome, column item]:
   - outcome:     '000'          Call 000
                  'poisons'      Call 000, or the Poisons Information Centre
                  'out-of-scope' Not a SWIFT walk-in: phone number and 000 text
                  'call-first'   Call SWIFT first (shows the SWIFT number only)
                  'swift'        Come to SWIFT
                  'dental'       The independent dental practice in our building
                  'gp'           See your GP
   - column item: which line in the three 'Where to go' columns to highlight (see ITEMS
                  on the homepage), or null.
   An optional fourth field adds a note: 'age' reminds that SWIFT sees ages 3 months and up.

   INTERIM ROUTING until clinical sign-off (items 3.3 to 3.5):
   - Chest pain and breathing terms go to 'call-first'. They will open the chest pain or
     shortness of breath screening panel once those are approved.
   - Headache, abdominal pain, fever, dizziness/vertigo and fainting go to 'call-first'.
     They will become 'swift' with a 'Call 000 if...' red-flag box once those are approved.
   - Terms that match the draft red flags outright (stroke signs, vomiting blood and so on)
     go to '000'. */
window.SWIFT_SYMPTOMS = [
  // Chest and breathing (screening panel applies; interim: call SWIFT first)
  ['chest pain', 'call-first', 'chest'],
  ['chest tightness', 'call-first', 'chest'],
  ['chest pressure', 'call-first', 'chest'],
  ['chest discomfort', 'call-first', 'chest'],
  ['heart pain', 'call-first', 'chest'],
  ['pain in my chest', 'call-first', 'chest'],
  ['angina', 'call-first', 'chest'],
  ['cardiac pain', 'call-first', 'chest'],
  ['palpitations', 'call-first', 'chest'],
  ['racing heart', 'call-first', 'chest'],
  ['heart flutter', 'call-first', 'chest'],
  ['irregular heartbeat', 'call-first', 'chest'],
  ['tachycardia', 'call-first', 'chest'],
  ['short of breath', 'call-first', 'chest'],
  ['shortness of breath', 'call-first', 'chest'],
  ["can't breathe", 'call-first', 'chest'],
  ['trouble breathing', 'call-first', 'chest'],
  ['breathless', 'call-first', 'chest'],
  ['out of breath', 'call-first', 'chest'],
  ['dyspnoea', 'call-first', 'chest'],
  ['wheeze', 'call-first', 'chest'],
  ['wheezing', 'call-first', 'chest'],
  ['asthma', 'call-first', 'chest'],
  ['asthma attack', 'call-first', 'chest'],
  ['tight chest', 'call-first', 'chest'],
  ['cough', 'call-first', 'chest'],
  ['bad cough', 'call-first', 'chest'],
  ['coughing blood', 'call-first', 'chest'],
  ['haemoptysis', 'call-first', 'chest'],
  ['chest infection', 'call-first', 'chest'],
  ['bronchitis', 'call-first', 'chest'],
  ['pneumonia', 'call-first', 'chest'],

  // Head, neurological and dizziness
  ['headache', 'call-first', 'head'],
  ['bad headache', 'call-first', 'head'],
  ['migraine', 'call-first', 'head'],
  ['head pain', 'call-first', 'head'],
  ['worst headache', '000', 'stroke'],
  ['dizzy', 'call-first', 'head'],
  ['dizziness', 'call-first', 'head'],
  ['light-headed', 'call-first', 'head'],
  ['lightheaded', 'call-first', 'head'],
  ['giddy', 'call-first', 'head'],
  ['off balance', 'call-first', 'head'],
  ['unsteady', 'call-first', 'head'],
  ['vertigo', 'call-first', 'head'],
  ['spinning', 'call-first', 'head'],
  ['room spinning', 'call-first', 'head'],
  ['bppv', 'call-first', 'head'],
  ['faint', 'call-first', 'head'],
  ['fainted', 'call-first', 'head'],
  ['fainting', 'call-first', 'head'],
  ['passed out', 'call-first', 'head'],
  ['blackout', 'call-first', 'head'],
  ['black out', 'call-first', 'head'],
  ['collapse', 'call-first', 'head'],
  ['syncope', 'call-first', 'head'],
  ['presyncope', 'call-first', 'head'],
  ['near faint', 'call-first', 'head'],
  ['head injury', 'call-first', 'head'],
  ['hit my head', 'call-first', 'head'],
  ['concussion', 'call-first', 'head'],
  ['knocked out', 'call-first', 'head'],
  ['numbness', 'call-first', 'head'],
  ['tingling', 'call-first', 'head'],
  ['pins and needles', 'call-first', 'head'],
  ['weakness in arm or leg', '000', 'stroke'],
  ['slurred speech', '000', 'stroke'],
  ['facial droop', '000', 'stroke'],
  ['vision loss', '000', 'stroke'],
  ['double vision', 'call-first', 'head'],
  ['confusion', '000', 'stroke'],

  // Abdomen, gut and urinary
  ['abdominal pain', 'call-first', 'abdomen'],
  ['abdo pain', 'call-first', 'abdomen'],
  ['stomach pain', 'call-first', 'abdomen'],
  ['tummy pain', 'call-first', 'abdomen'],
  ['belly pain', 'call-first', 'abdomen'],
  ['stomach ache', 'call-first', 'abdomen'],
  ['cramps', 'call-first', 'abdomen'],
  ['right-sided abdominal pain', 'call-first', 'abdomen'],
  ['lower abdominal pain', 'call-first', 'abdomen'],
  ['appendicitis', 'call-first', 'abdomen'],
  ['gallstones', 'call-first', 'abdomen'],
  ['gallbladder', 'call-first', 'abdomen'],
  ['renal colic', 'call-first', 'abdomen'],
  ['kidney stone', 'call-first', 'abdomen'],
  ['flank pain', 'call-first', 'abdomen'],
  ['loin pain', 'call-first', 'abdomen'],
  ['vomiting', 'swift', 'gut'],
  ['throwing up', 'swift', 'gut'],
  ['nausea', 'swift', 'gut'],
  ['diarrhoea', 'swift', 'gut'],
  ['diarrhea', 'swift', 'gut'],
  ['gastro', 'swift', 'gut'],
  ['food poisoning', 'swift', 'gut'],
  ['dehydration', 'swift', 'gut'],
  ['constipation', 'swift', 'gut'],
  ['blood in stool', '000', 'bleeding'],
  ['black stool', '000', 'bleeding'],
  ['vomiting blood', '000', 'bleeding'],
  ['uti', 'swift', 'urinary'],
  ['urinary infection', 'swift', 'urinary'],
  ['burning when i pee', 'swift', 'urinary'],
  ['dysuria', 'swift', 'urinary'],
  ['blood in urine', 'swift', 'urinary'],
  ['haematuria', 'swift', 'urinary'],
  ['painful urination', 'swift', 'urinary'],
  ["can't pee", 'swift', 'urinary'],
  ['urinary retention', 'swift', 'urinary'],
  ['testicular pain', 'call-first', 'urinary'],
  ['groin pain', 'swift', 'urinary'],
  ['hernia', 'swift', 'urinary'],
  ['lump in groin', 'swift', 'urinary'],

  // Fever and infection
  ['fever', 'call-first', 'fever', 'age'],
  ['high temperature', 'call-first', 'fever', 'age'],
  ['temperature', 'call-first', 'fever', 'age'],
  ['chills', 'call-first', 'fever', 'age'],
  ['rigors', 'call-first', 'fever', 'age'],
  ['shivering', 'call-first', 'fever', 'age'],
  ['sweats', 'call-first', 'fever', 'age'],
  ['febrile', 'call-first', 'fever', 'age'],
  ['child with fever', 'call-first', 'fever', 'age'],
  ['baby fever', 'call-first', 'fever', 'age'],
  ['kids fever', 'call-first', 'fever', 'age'],
  ['febrile child', 'call-first', 'fever', 'age'],
  ['flu', 'swift', 'fever'],
  ['influenza', 'swift', 'fever'],
  ['covid', 'swift', 'fever'],
  ['covid positive', 'swift', 'fever'],
  ['sore throat', 'swift', 'ent'],
  ['tonsillitis', 'swift', 'ent'],
  ['strep throat', 'swift', 'ent'],
  ['ear pain', 'swift', 'ent'],
  ['earache', 'swift', 'ent'],
  ['otitis', 'swift', 'ent'],
  ['eye infection', 'swift', 'ent'],
  ['red eye', 'swift', 'ent'],
  ['sinus pain', 'swift', 'ent'],
  ['sinusitis', 'swift', 'ent'],
  ['cellulitis', 'swift', 'skin'],
  ['skin infection', 'swift', 'skin'],
  ['abscess', 'swift', 'skin'],
  ['boil', 'swift', 'skin'],
  ['infected wound', 'swift', 'skin'],
  ['red swollen skin', 'swift', 'skin'],
  ['insect bite', 'swift', 'skin'],
  ['tick bite', 'swift', 'skin'],
  ['spider bite', 'swift', 'skin'],

  // Injury and wounds
  ['sprain', 'swift', 'injury'],
  ['strain', 'swift', 'injury'],
  ['twisted ankle', 'swift', 'injury'],
  ['rolled ankle', 'swift', 'injury'],
  ['sore wrist', 'swift', 'injury'],
  ['sore knee', 'swift', 'injury'],
  ['knee injury', 'swift', 'injury'],
  ['shoulder injury', 'swift', 'injury'],
  ['sports injury', 'swift', 'injury'],
  ['back pain', 'swift', 'back'],
  ['neck pain', 'swift', 'back'],
  ['whiplash', 'swift', 'back'],
  ['broken bone', 'swift', 'injury'],
  ['fracture', 'swift', 'injury'],
  ['suspected fracture', 'swift', 'injury'],
  ['dislocation', 'swift', 'injury'],
  ['dislocated shoulder', 'swift', 'injury'],
  ['broken finger', 'swift', 'injury'],
  ['broken toe', 'swift', 'injury'],
  ['broken wrist', 'swift', 'injury'],
  ['deep cut', 'swift', 'wounds'],
  ['laceration', 'swift', 'wounds'],
  ['needs stitches', 'swift', 'wounds'],
  ['gash', 'swift', 'wounds'],
  ['bleeding cut', 'swift', 'wounds'],
  ['wound', 'swift', 'wounds'],
  ['split skin', 'swift', 'wounds'],
  ['burn', 'swift', 'wounds'],
  ['scald', 'swift', 'wounds'],
  ['minor burn', 'swift', 'wounds'],
  ['sunburn', 'swift', 'wounds'],
  ['blister', 'swift', 'wounds'],
  ['foreign body', 'swift', 'foreign'],
  ['splinter', 'swift', 'foreign'],
  ['fish hook', 'swift', 'foreign'],
  ['object in eye', 'swift', 'foreign'],
  ['something stuck', 'swift', 'foreign'],
  ['swallowed object', 'call-first', 'foreign'],
  ['animal bite', 'swift', 'skin'],
  ['dog bite', 'swift', 'skin'],
  ['cat bite', 'swift', 'skin'],
  ['needlestick', 'swift', 'wounds'],
  ['nail through foot', 'swift', 'wounds'],
  ['car accident', 'call-first', 'injury'],
  ['fall', 'swift', 'injury'],
  ['sports collision', 'swift', 'injury'],

  // Allergy, skin and other
  ['allergic reaction', 'swift', 'allergy'],
  ['hives', 'swift', 'allergy'],
  ['urticaria', 'swift', 'allergy'],
  ['rash', 'swift', 'allergy'],
  ['itchy rash', 'swift', 'allergy'],
  ['swollen lip', 'call-first', 'allergy'],
  ['swelling', 'swift', 'allergy'],
  ['anaphylaxis', '000', 'anaphylaxis'],
  ['bee sting', 'swift', 'allergy'],
  ['nosebleed', 'swift', 'ent'],
  ['epistaxis', 'swift', 'ent'],
  ['eye injury', 'swift', 'foreign'],
  ['toothache', 'dental', null],
  ['leg swelling', 'swift', 'leg'],
  ['calf pain', 'swift', 'leg'],
  ['dvt', 'swift', 'leg'],
  ['painful swollen leg', 'swift', 'leg'],
  ["can't keep fluids down", 'swift', 'gut'],
  ['poisoning', 'poisons', 'overdose'],

  // Route to See your GP
  ['prescription', 'gp', 'prescriptions'],
  ['repeat script', 'gp', 'prescriptions'],
  ['medical certificate', 'gp', 'certificates'],
  ['work certificate', 'gp', 'certificates'],
  ['referral', 'gp', 'referrals'],
  ['test results', 'gp', 'referrals'],
  ['blood test results', 'gp', 'referrals'],
  ['vaccination', 'gp', 'vaccination'],
  ['flu shot', 'gp', 'vaccination'],
  ['check-up', 'gp', 'vaccination'],
  ['blood pressure check', 'gp', 'vaccination'],
  ['mild cold', 'gp', 'cold'],
  ['runny nose', 'gp', 'cold'],
  ['long-term condition', 'gp', 'ongoing'],
  ['diabetes review', 'gp', 'ongoing'],
  ['mental health plan', 'gp', 'mentalplan'],

  // Route to Call 000 directly
  ['stroke', '000', 'stroke'],
  ['heart attack', '000', 'heart'],
  ['unconscious', '000', 'unconscious'],
  ['not breathing', '000', 'unconscious'],
  ['seizure', '000', 'seizure'],
  ['fit', '000', 'seizure'],
  ['choking', '000', 'choking'],
  ['severe bleeding', '000', 'bleeding'],
  ['overdose', '000', 'overdose'],
  ['suicidal', '000', 'selfharm'],
  ['thoughts of self-harm', '000', 'selfharm'],
  ['severe allergic reaction', '000', 'anaphylaxis'],
  ['major trauma', '000', 'trauma'],

  // Out of scope (no walk-in result)
  ['pregnancy bleeding', 'out-of-scope', null],
  ['pregnant with pain', 'out-of-scope', null],
  ['labour', 'out-of-scope', null],
  ['baby under 3 months', 'out-of-scope', null],
  ['newborn unwell', 'out-of-scope', null],
  ['severe mental health crisis', 'out-of-scope', null]
];
